version: v26.2.0

namespaces:
  location: file:///home/ory/namespaces.ts
  experimental_strict_mode: true

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

log:
  level: info
  format: json
  leak_sensitive_values: false
