serve:
  public:
    base_url: http://localhost:24455/
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://localhost:24455/
  allowed_return_urls:
    - http://localhost:24455
    - http://localhost:4200
  flows:
    error:
      ui_url: http://localhost:24455/ui/error
    settings:
      ui_url: http://localhost:24455/ui/settings
    recovery:
      ui_url: http://localhost:24455/ui/recovery
      after:
        hooks:
          - hook: web_hook
            config:
              url: http://host.docker.internal:3400/internal/hooks/invitation-activated
              method: POST
              body: file:///etc/config/kratos/invitation-activated.jsonnet
              response:
                ignore: false
              auth:
                type: api_key
                config:
                  name: Authorization
                  value: Bearer local-only-hook-secret-32-bytes
                  in: header
    verification:
      ui_url: http://localhost:24455/ui/verification
    logout:
      after:
        default_browser_return_url: http://localhost:24455/
    login:
      ui_url: http://localhost:24455/ui/login
    registration:
      ui_url: http://localhost:24455/ui/invitation
