server {
  listen 8080;
  server_name _;
  absolute_redirect off;

  location = / {
    return 302 /ui/v2/login;
  }

  location /assets/ {
    proxy_set_header Host auth.ensombl.io;
    proxy_set_header X-ZITADEL-Instance-Host auth.ensombl.io;
    proxy_set_header X-ZITADEL-Public-Host $host;
    proxy_set_header X-Forwarded-Host $host;
    proxy_set_header X-Forwarded-Proto https;
    proxy_pass http://zitadel-api:8080;
  }

  location / {
    return 404;
  }
}
