serve:
  public:
    base_url: https://auth.freightclaims.com/

selfservice:
  default_browser_return_url: https://auth.freightclaims.com/
  flows:
    error:
      ui_url: https://auth.freightclaims.com/ui/error
    settings:
      ui_url: https://auth.freightclaims.com/ui/settings
    recovery:
      ui_url: https://auth.freightclaims.com/ui/recovery
    verification:
      ui_url: https://auth.freightclaims.com/ui/verification
    logout:
      after:
        default_browser_return_url: https://auth.freightclaims.com/
    login:
      ui_url: https://auth.freightclaims.com/ui/login
    registration:
      ui_url: https://auth.freightclaims.com/ui/invitation
