serve:
  cookies:
    same_site_mode: Lax
    secure: true

urls:
  self:
    issuer: https://auth.ensombl.io/
    public: https://auth.ensombl.io/
    admin: http://hydra-admin:4445/
  login: https://auth.ensombl.io/ui/oauth2/login
  consent: https://auth.ensombl.io/ui/oauth2/consent
  logout: https://auth.ensombl.io/ui/oauth2/logout
  error: https://auth.ensombl.io/ui/error
  post_logout_redirect: https://auth.ensombl.io/
  identity_provider:
    url: http://kratos-admin:4434/
    publicUrl: https://auth.ensombl.io/

secrets:
  system:
    - local-only-hydra-system-secret-change-me

oidc:
  subject_identifiers:
    supported_types:
      - public
      - pairwise
    pairwise:
      salt: local-only-pairwise-salt-change-me

oauth2:
  expose_internal_errors: false
  allowed_top_level_claims:
    - aud
    - auth_time
    - email
    - email_verified
    - family_name
    - given_name
    - iss
    - jti
    - name
    - nonce
    - rat
    - sid
    - sub

ttl:
  login_consent_request: 15m
  auth_code: 10m
  access_token: 1h
  refresh_token: 720h
  id_token: 1h

log:
  level: info
  format: json
  leak_sensitive_values: false
